import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, writeFile, readFile, readdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { spawnSync } from 'node:child_process';
import { routes, plan, passed } from './fixtures.mjs';

const tool = resolve('plugins/idea2run/skills/idea2run/scripts/idea2run.mjs');
test('命令行完成中文空格路径的交接、反馈与导出，并拒绝覆盖', async (context) => {
  const directory = await mkdtemp(join(tmpdir(), 'idea2run-测试 with spaces-'));
  context.after(() => rm(directory, { recursive: true, force: true }));
  const session = join(directory, '进度.json');
  const json = async (name, value) => { const path = join(directory, name); await writeFile(path, `\uFEFF${JSON.stringify(value)}`); return path; };
  const run = (...args) => spawnSync(process.execPath, [tool, ...args], { encoding: 'utf8', cwd: directory });
  const ok = (...args) => { const result = run(...args); assert.equal(result.status, 0, result.stderr); return result.stdout; };
  assert.match(ok('--help'), /不执行/);
  ok('init', session, '--idea', '测试想法，文本含 $() 与空格');
  assert.notEqual(run('init', session, '--idea', '不要覆盖').status, 0);
  assert.equal(JSON.parse(await readFile(session)).idea, '测试想法，文本含 $() 与空格');
  ok('routes', session, await json('候选.json', routes));
  assert.notEqual(run('select', session, 'simple').status, 0);
  ok('select', session, 'simple', '--confirmed');
  ok('plan', session, await json('计划.json', plan));
  assert.notEqual(run('prompt', session).status, 0);
  assert.match(ok('prompt', session, '--preview'), /审阅草稿/);
  const reviewExport = join(directory, '审阅导出');
  ok('export', session, reviewExport);
  assert.deepEqual((await readdir(reviewExport)).sort(), ['plan.md', 'session.json']);
  ok('approve', session, '--confirmed');
  ok('agent', session, 'yes', '--confirmed');
  assert.match(ok('prompt', session), /检查测试输入/);
  ok('result', session, 'inspect', await json('结果.json', passed('input')));
  assert.notEqual(run('prompt', session).status, 0);
  ok('authorize', session, 'configure', '--confirmed');
  const exportDirectory = join(directory, '执行导出');
  ok('export', session, exportDirectory);
  const original = await readFile(join(exportDirectory, 'plan.md'), 'utf8');
  assert.match(await readFile(join(exportDirectory, 'current-prompt.md'), 'utf8'), /写入测试产物/);
  assert.notEqual(run('export', session, exportDirectory).status, 0);
  assert.equal(await readFile(join(exportDirectory, 'plan.md'), 'utf8'), original);
  assert.notEqual(run('prompt', session, '--unknown').status, 0);
  assert.notEqual(run('show', session, '--confirmed').status, 0);
  ok('result', session, 'configure', await json('结果2.json', passed('output')));
  assert.match(ok('show', session), /reported_complete/);
});

test('技能安装只写入指定项目，重复安装不覆盖', async (context) => {
  const directory = await mkdtemp(join(tmpdir(), 'idea2run-install-'));
  context.after(() => rm(directory, { recursive: true, force: true }));
  const installer = resolve('scripts/install-skill.mjs');
  const run = () => spawnSync(process.execPath, [installer, directory], { encoding: 'utf8' });
  assert.equal(run().status, 0);
  const skill = join(directory, '.agents', 'skills', 'idea2run', 'SKILL.md');
  const original = await readFile(skill, 'utf8');
  assert.match(original, /name: idea2run/);
  assert.equal(run().status, 1);
  assert.equal(await readFile(skill, 'utf8'), original);
});
